# Generated by Django 5.0.4 on 2025-07-28 10:50

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSurvey',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(help_text='Название вашего опроса', max_length=200, verbose_name='Название опроса')),
                ('google_form_url', models.URLField(help_text='Полная ссылка на Google Form для этого опроса', max_length=500, validators=[django.core.validators.URLValidator(message='Введите корректную ссылку на Google Form')], verbose_name='Ссылка на Google Form')),
                ('description', models.TextField(blank=True, help_text='Краткое описание опроса', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли опрос пользователям', verbose_name='Активен')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'historical Опрос',
                'verbose_name_plural': 'historical Опросы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название вашего опроса', max_length=200, verbose_name='Название опроса')),
                ('google_form_url', models.URLField(help_text='Полная ссылка на Google Form для этого опроса', max_length=500, validators=[django.core.validators.URLValidator(message='Введите корректную ссылку на Google Form')], verbose_name='Ссылка на Google Form')),
                ('description', models.TextField(blank=True, help_text='Краткое описание опроса', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли опрос пользователям', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'surveys_survey',
                'ordering': ['-created_at'],
            },
        ),
    ]
