# Generated by Django 5.0.4 on 2025-07-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_historicalsurvey_slug_survey_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Автоматически генерируется из названия', max_length=200, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
