# Generated by Django 5.0.4 on 2025-07-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_survey_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsurvey',
            name='is_login_req',
            field=models.BooleanField(default=False, help_text='Требуется ли авторизация через NII EDU для доступа к опросу', verbose_name='Требуется авторизация'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_login_req',
            field=models.BooleanField(default=False, help_text='Требуется ли авторизация через NII EDU для доступа к опросу', verbose_name='Требуется авторизация'),
        ),
    ]
